### PR TITLE
fix: only delete gc related labels

### LINKED ISSUE #200: Nydus driver convert image failed with nydus-image v2.2.x
When update `nydus-image` from `v2.1.6` to `v2.2.x`, `acceld` convert nydus image failed.
b6d609666985ee841df81cb0655624ef

### PR DESCRIPTION
**Pull request by Desiki-high**
Some labels are used by image build and so on. We should only delete the gc related labels.

resolve #200

### CODE REVIEW

File: script/integration/nydus/test.sh [hunk 1]
```diff
@@ -17,7 +17,6 @@ sudo /usr/bin/nydusify check \
   --nydusd /usr/bin/nydusd \
   --source localhost/library/$OCI_IMAGE_NAME:latest \
   --target localhost/library/$OCI_IMAGE_NAME:latest-nydus \
-  --backend-type registry \
   --backend-config "{\"scheme\":\"http\",\"host\":\"localhost\",\"repo\":\"library/$OCI_IMAGE_NAME\",\"auth\":\"YWRtaW46SGFyYm9yMTIzNDU=\"}"
```
Comment (imeoer) [inline script/integration/nydus/test.sh:20]: Also remove this?

File: script/integration/one-time.sh [hunk 2]
```diff
@@ -13,5 +13,4 @@ sudo /usr/bin/nydusify check \
   --nydusd /usr/bin/nydusd \
   --source localhost/library/$OCI_IMAGE_NAME:latest \
   --target localhost/library/$OCI_IMAGE_NAME:latest-nydus \
-  --backend-type registry \
   --backend-config "{\"scheme\":\"http\",\"host\":\"localhost\",\"repo\":\"library/$OCI_IMAGE_NAME\",\"auth\":\"YWRtaW46SGFyYm9yMTIzNDU=\"}"
```
Comment (imeoer) [inline script/integration/one-time.sh:16]: Ditto.

File: script/integration/nydus/test.sh (hunk 1 above)
Comment (Desiki-high) [reply script/integration/nydus/test.sh]: fixed.

**Review by imeoer — APPROVED** [review]
