### PR TITLE
fix: wrap content store in upper level 

### LINKED ISSUE #163: content store wrapped incompletely
content store wrapped containerd Content Store. But unfortunately, if we use the `provider. contentStore()` method to obtain the store, it will call `db. contentStore()`, which is another layer of wrap on the `containerd content Store`.

Then the methods like Info(), Update() we called is not the the methods we wrapped in content store.

### PR DESCRIPTION
**Pull request by Desiki-high**
Fix #163.

Changes:
- move bucket related code to ```bucket.go```.
- wrap content store in upper level: ```Content```.

### CODE REVIEW

File: pkg/content/content.go [hunk 1]
```diff
@@ -16,36 +16,34 @@ package content
...
-	bucketKeyObjectContent = []byte("content")
-	bucketKeyObjectBlob    = []byte("blob")
-
-	bucketKeySize      = []byte("size")
-	bucketKeyUpdatedAt = []byte("updatedat")
-)
-
 type Content struct {
-	db        *metadata.DB
+	//db is the bolt database of content
```
Comment (imeoer) [inline pkg/content/content.go:34]: Need to add a space after "//". others LGTM, thanks for the fixup.

**Review by imeoer — APPROVED** [review]
